### ISSUE TITLE
不知道是否可以告知下，在微信6.3.22版本中hook如何不引发crash?

### ISSUE THREAD

**Issue by 231599447** [fkzhang/WechatUnrecalled#113]
`		String className = "com.tencent.mm.sdk.platformtools.v";
		String methodName="d"
`
仅HOOK了一个日志功能。

引发的错误日志：
`11-13 14:14:54.318: E/AndroidRuntime(2440): java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at com.tencent.mm.sdk.platformtools.v.<clinit>(SourceFile:52)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at com.tencent.mm.app.MMApplicationLifeCycle.setPatchRev(SourceFile:61)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at com.tencent.mm.app.MMApplicationLifeCycle.onBaseContextAttached(SourceFile:70)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(SourceFile:124)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(SourceFile:138)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at android.app.Application.attach(Application.java:147)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1053)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1037)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:499)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4613)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at android.app.ActivityThread.handleBindApplication(Native Method)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at android.app.ActivityThread.access$1300(ActivityThread.java:165)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1433)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at android.os.Handler.dispatchMessage(Handler.java:107)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at android.os.Looper.loop(Looper.java:194)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at android.app.ActivityThread.main(ActivityThread.java:5391)
11-13 14:14:54.318: E/AndroidRuntime(2440): 	at java.lang.reflect.Method.invokeNative(Native Method)
`

**Comment by vipzrx** [comment]
只是一个报错，不好定位你的问题。请详细描述下你的设置、流程、以及复现的过程

xpsoed的开发有个小群，需要的话，加我微信“qq123862905” ，回复： “Xposed”
