### ISSUE TITLE
导出语音失败

### ISSUE THREAD

**Issue by JasonKhew96** [fkzhang/WechatUnrecalled#320]
```
06-09 18:20:26.489 E/Xposed  (11552): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
06-09 18:20:26.489 E/Xposed  (11552): 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7313)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1161)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.view.View.requestLayout(View.java:21995)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.view.View.requestLayout(View.java:21995)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.view.View.requestLayout(View.java:21995)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.view.View.requestLayout(View.java:21995)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.view.View.requestLayout(View.java:21995)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.view.View.requestLayout(View.java:21995)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.view.View.requestLayout(View.java:21995)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.view.View.requestLayout(View.java:21995)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.view.View.requestLayout(View.java:21995)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.view.View.setFlags(View.java:13343)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.view.View.setVisibility(View.java:9420)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.widget.ImageView.setVisibility(ImageView.java:1608)
06-09 18:20:26.489 E/Xposed  (11552): 	at com.fkzhang.wechatxposedhooks.i.m$240.run(Unknown Source:60)
06-09 18:20:26.489 E/Xposed  (11552): 	at com.fkzhang.wechatxposedhooks.c.i$3.run(Unknown Source:2)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.os.Handler.handleCallback(Handler.java:790)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.os.Looper.loop(Looper.java:164)
06-09 18:20:26.489 E/Xposed  (11552): 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

3秒以上的语音都导出失败

**Comment by JasonKhew96** [comment]
已解决
