### ISSUE TITLE
qx2.3  使用一段时间后突然无法加载

### ISSUE THREAD

**Issue by bluedream1228** [fkzhang/WechatUnrecalled#434]
报告xposed没有安装框架。但之前正常，而且wxposed也正常。小米k20pro magisk+edxposed。

**Comment by bluedream1228** [comment]
03-12 13:56:43.978  7215  7215 I EdXposedManager: ModuleUtil -> updating modules.list
03-12 13:57:10.150 11381 11381 I EdXposed-Bridge: hook: com.tencent.mobileqq
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.tencent.mobileqq/files/e8d59794b1e6207d425ea355113cd3dc" is 64-bit instead of 32-bit
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at java.lang.Runtime.load0(Runtime.java:938)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at java.lang.System.load(System.java:1631)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.QxCoreLoader.<init>(Unknown Source:105)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.qqxposed.יˎ.ـﹳ(Unknown Source:26)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ˋˋ$יˎ.run(Unknown Source:107)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:883)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:224)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7520)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.Object com.fkzhang.xposed.hook.QxCoreLoader.CallMethod(int, java.lang.Object[]) (tried Java_com_fkzhang_xposed_hook_QxCoreLoader_CallMethod and Java_com_fkzhang_xposed_hook_QxCoreLoader_CallMethod__I_3Ljava_lang_Object_2)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.QxCoreLoader.CallMethod(Native Method)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.QxCoreLoader.ـﹳ(Unknown Source:0)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.QxCoreLoader.<init>(Unknown Source:184)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.qqxposed.יˎ.ـﹳ(Unknown Source:26)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ˋˋ$יˎ.run(Unknown Source:107)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:883)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:224)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7520)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-12 13:57:10.625 11381 11381 I EdXposed-Bridge: com.tencent.mobileqq loading com.fkzhang.qqxposed
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.Object com.fkzhang.xposed.hook.QxCoreLoader.CallMethod(int, java.lang.Object[]) (tried Java_com_fkzhang_xposed_hook_QxCoreLoader_CallMethod and Java_com_fkzhang_xposed_hook_QxCoreLoader_CallMethod__I_3Ljava_lang_Object_2)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.QxCoreLoader.CallMethod(Native Method)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.QxCoreLoader.ـﹳ(Unknown Source:0)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.QxCoreLoader.ـﹳ(Unknown Source:11)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ﹳⁱ.יˎ(Unknown Source:3)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ﹳⁱ.יˎ(Unknown Source:1)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.QxCoreLoader.ˋˋ(Unknown Source:14)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.qqxposed.יˎ.ـﹳ(Unknown Source:2)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.fkzhang.xposed.hook.ˋˋ$יˎ.run(Unknown Source:160)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:883)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:224)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7520)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-12 13:57:10.625 11381 11381 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-12 13:57:10.625 11381 11381 I EdXposed-Bridge: com.fkzhang.qqxposed load hooks failed!
03-12 13:57:10.632 11381 11381 I EdXposed-Bridge: com.fkzhang.qqxposed load time: 21
