### ISSUE TITLE
WX设置界面不显示，求教

### ISSUE THREAD

**Issue by w2131978** [fkzhang/WechatUnrecalled#476]
试过play7.021 国内7.022 8.0，WX 17 18 19版，甚至把EDXP都换成了LSP，都没法显示WX界面用不了，求指导

02-03 15:39:06.612  9494  9494 I LSPosed : Start to install inline hooks
02-03 15:39:06.612  9494  9494 I LSPosed : Using api level 29
02-03 15:39:06.612  9494  9494 I LSPosed : Start to install Riru hook
02-03 15:39:06.662  9494  9494 I LSPosed : Riru hooks installed
02-03 15:39:06.683  9494  9494 I LSPosed : ART hooks installed
02-03 15:39:06.691  9494  9494 I LSPosed : LSP Variant: 1
02-03 15:39:06.717  9494  9494 I LSPosed : Loading modules for com.tencent.mm
02-03 15:39:06.744  9494  9494 I LSPosed-Bridge: Loading modules from /data/app/com.fkzhang.wechatxposed-yiXGHnr5HwO7W5IpuGHUPg==/base.apk
02-03 15:39:06.746  9494  9494 I LSPosed-Bridge:   Loading class com.fkzhang.wechatxposed.XposedInit
02-03 15:39:06.747  9494  9494 I LSPosed-Bridge: Loading modules from /data/app/com.surcumference.fingerprintpay-XSWR1_qC52k57CESa7yVRw==/base.apk
02-03 15:39:06.749  9494  9494 I LSPosed-Bridge:   Loading class com.yyxx.wechatfp.xposed.WalletBaseUI
02-03 15:39:06.956  9494  9494 I LSPosed-Bridge: WeChatFp [initWechat](WalletBaseUI.java:52) loaded: [com.tencent.mm] version:3.9.22
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: android.content.pm.PackageManager$NameNotFoundException: Application package com.fkzhang.wechatxposed not found
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2233)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2204)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at ـˈ.ʻˊ.ʻˊ.ʻˊ.ᵔˏ.ـˈ(Unknown Source:5)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at com.fkzhang.xposed.hook.ﹳᵢ.ـˈ(Unknown Source:34)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at com.fkzhang.xposed.hook.ﹳᵢ.ʻˊ(Unknown Source:0)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at com.fkzhang.wechatxposed.XposedInit.handleLoadPackage(Unknown Source:17)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at io.github.lsposed.lspd._hooker.impl.LoadedApkGetCL.afterHookedMethod(LoadedApkGetCL.java:58)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at de.robv.android.xposed.LspHooker.handleHookedMethod(LspHooker.java:94)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at LspHooker_d80f73e34da17c301b40feab7995d5a6a0b56621.hook(Unknown Source:45)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at android.app.LoadedApk.getResources(LoadedApk.java:1188)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:2499)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at android.app.ContextImpl.createAppContext(ContextImpl.java:2491)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6497)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at de.robv.android.xposed.LspHooker.handleHookedMethod(LspHooker.java:81)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at LspHooker_42b8453bf7df105343083f1377c32094be493c49.hook(Unknown Source:48)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at android.app.ActivityThread.access$1600(ActivityThread.java:231)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1952)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at android.os.Looper.loop(Looper.java:214)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
02-03 15:39:07.085  9494  9494 E LSPosed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
02-03 15:39:07.385  9494  9494 I LSPosed-Bridge: WeChatFp [getTraceTag](L.java:81) Application onCreate
02-03 15:39:07.390  9494  9494 I LSPosed-Bridge: WeChatFp [getTraceTag](L.java:81) Xposed plugin init version: 3.9.22
02-03 15:39:07.403  9494  9494 I LSPosed-Bridge: WeChatFp [getTraceTag](L.java:81) WeChat Version code:1820
02-03 15:39:07.476  9494  9494 I LSPosed-Bridge: WeChatFp [getTraceTag](L.java:81) Activity onResume =	com.tencent.mm.splash.i@cb71b21	
02-03 15:39:07.924  9494  9494 I LSPosed-Bridge: WeChatFp [getTraceTag](L.java:81) Activity onPause =	com.tencent.mm.splash.i@cb71b21	
02-03 15:39:08.045  9494  9494 I LSPosed-Bridge: WeChatFp [getTraceTag](L.java:81) Activity onResume =	com.tencent.mm.app.WeChatSplashActivity@f2ce425	
02-03 15:39:08.803  9807  9807 I LSPosed : Start to install inline hooks
02-03 15:39:08.803  9807  9807 I LSPosed : Using api level 29

**Comment by w2131978** [comment]
折腾了一个多星期的问题突然自己搞定了，我禁了微信查看其他应用信息的权限，恢复之后WX就正常了。。。大佬也麻烦看看这类问题有没有规避方案，毕竟放任微信读应用列表好像确实也不太安全
