### ISSUE TITLE
大神 LSP框架出错提示 有些代码是显示为未知

### ISSUE THREAD

**Issue by msfbao** [fkzhang/WechatUnrecalled#483]
现在遇到的问题是有时微x可以自定义铃声有时就失效
附上LSP日记 请大佬看看 如果有空看可以修复下这功能
用的微信版本是 7.03谷歌版（如果可以请支持新微信的自定义铃声这个功能对我工作很重要）
现附上部份代码  还有我的手机时间是下午5点多了 [时间还是显示为早上9点多这是什么情况]
LSPosed Log
--------- beginning of information
Manufacturer: Xiaomi
Brand: Xiaomi
Device: cmi
Product: cmi
Model: Mi 10 Pro
Fingerprint: Xiaomi/cmi/cmi:10/QKQ1.200419.002/20.7.4:user/release-keys
ROM description: cmi-user 10 QKQ1.200419.002 20.7.4 release-keys
Architecture: arm64-v8a
Android build: QKQ1.200419.002
Android version: 10
Android sdk: 29
LSPosed version: v1.2.0
LSPosed version code: 5381
LSPosed api: 93
Riru version: v23.6 (56)
Riru api: 10
Magisk: 20.4 (20400)
2021-03-03 09:30:13.013 6914-6914/com.tencent.mm LSPosedBridge: com.tencent.mm loading com.fkzhang.wechatxposed
2021-03-03 09:30:22.022 6914-6914/com.tencent.mm LSPosedBridge: com.fkzhang.wechatxposed [WechatXposed](2.17|77): wechat version 7.0.3(1381)
2021-03-03 09:30:22.022 6914-6914/com.tencent.mm LSPosedBridge: com.fkzhang.wechatxposed load time: 8502
2021-03-03 09:30:22.022 6914-7045/com.tencent.mm LSPosedBridge: 微X模块 2.17_3.17 (6,87) p
2021-03-03 09:30:22.022 6914-7057/com.tencent.mm LSPosedBridge: feature loaded: base 155
2021-03-03 09:30:22.022 6914-7045/com.tencent.mm LSPosedBridge: Wechat: 7.0.3_1381 <PLAY> (0x27000340)[14bfea06]
2021-03-03 09:30:24.024 7476-7476/com.tencent.mobileqq LSPosedBridge: com.tencent.mobileqq loading com.fkzhang.qqxposed
2021-03-03 09:30:26.026 7476-7476/com.tencent.mobileqq LSPosedBridge: QX模块 2.7_1.12(42,1)
2021-03-03 09:30:26.026 7476-7476/com.tencent.mobileqq LSPosedBridge: com.fkzhang.qqxposed (2.7): QQ version 8.5.5(1630)
2021-03-03 09:30:26.026 7476-7476/com.tencent.mobileqq LSPosedBridge: com.fkzhang.qqxposed load time: 2365
2021-03-03 09:30:57.057 10525-10525/com.tencent.mm LSPosedBridge: com.tencent.mm loading com.fkzhang.wechatxposed
2021-03-03 09:31:01.001 10525-10525/com.tencent.mm LSPosedBridge: com.fkzhang.wechatxposed [WechatXposed](2.17|77): wechat version 7.0.3(1381)
2021-03-03 09:31:01.001 10525-10525/com.tencent.mm LSPosedBridge: com.fkzhang.wechatxposed load time: 3969
2021-03-03 09:31:01.001 10525-10643/com.tencent.mm LSPosedBridge: 微X模块 2.17_3.17 (6,87) p
2021-03-03 09:31:02.002 10525-10643/com.tencent.mm LSPosedBridge: Wechat: 7.0.3_1381 <PLAY> (0x27000340)[14bfea06]
2021-03-03 09:31:02.002 10525-10656/com.tencent.mm LSPosedBridge: feature loaded: base 155
2021-03-03 09:31:08.008 11544-11544/com.tencent.mobileqq LSPosedBridge: com.tencent.mobileqq loading com.fkzhang.qqxposed
2021-03-03 09:31:12.012 11544-11544/com.tencent.mobileqq LSPosedBridge: QX模块 2.7_1.12(42,1)
2021-03-03 09:31:12.012 11544-11544/com.tencent.mobileqq LSPosedBridge: com.fkzhang.qqxposed (2.7): QQ version 8.5.5(1630)
2021-03-03 09:31:12.012 11544-11544/com.tencent.mobileqq LSPosedBridge: com.fkzhang.qqxposed load time: 3637
2021-03-03 09:31:17.017 11993-11993/com.tencent.mobileqq LSPosedBridge: com.tencent.mobileqq loading com.fkzhang.qqxposed
2021-03-03 09:31:20.020 11993-11993/com.tencent.mobileqq LSPosedBridge: QX模块 2.7_1.12(42,1)
2021-03-03 09:31:20.020 11993-11993/com.tencent.mobileqq LSPosedBridge: com.fkzhang.qqxposed (2.7): QQ version 8.5.5(1630)
2021-03-03 09:31:20.020 11993-11993/com.tencent.mobileqq LSPosedBridge: com.fkzhang.qqxposed load time: 2897
2021-03-03 09:31:26.026 6914-7003/com.tencent.mm LSPosedBridge: java.lang.NoSuchMethodError: com.tencent.mm.storage.u#()#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:463)
	at com.fkzhang.wechatxposedhooks.ᵎˏ.ᵔﹶ$ʻʼ.ᵔﹶ(Unknown Source:15)
	at com.fkzhang.wechatxposedhooks.ﹳˏ.ᵎˏ.ˈـ(Unknown Source:28)
	at com.fkzhang.wechatxposedhooks.ﹳˏ.ᵎˏ.ᵎˏ(Unknown Source:16)
	at com.fkzhang.wechatxposedhooks.ﹳˏ.ᵎˏ.ٴʾ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ﹳˏ.ˎᵔ.ﹳˏ(Unknown Source:16)
	at com.fkzhang.wechatxposedhooks.Wrapper.FPB.go(Unknown Source:4)
	at java.lang.reflect.Method.invoke(Native Method)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ﹳʿ.ʽﹳ(:3)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ـﾞ.ʽﹳ(:2)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ـﾞ.ˎˊ(:1)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ᐧᐧ.ʿˎ(:2)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˑʾ.ˑᵢ.ˉˉ(Unknown Source:51)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˑʾ.ˑᵢ$ˊᵔ.ˎˊ(:1)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ˑʾ.ˎˊ(:1)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ﹳʿ.ﹳʿ(Unknown Source:16)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ﹳʿ.ʻـ(Unknown Source:33)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˑʾ.ʿᵢ.ˎˊ(:6)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ˑʾ.ˎˊ(:1)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ﹳʿ.ﹳʿ(Unknown Source:16)
	at com.fkzhang.wxfeatures.base.Wrapper.Init.publish(:2)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1283)
	at com.fkzhang.wechatxposedhooks.ᵎˏ.יᴵ.ᵎـ(Unknown Source:22)
	at com.fkzhang.wechatxposedhooks.ᵎˏ.ᵔﹶ.ˎⁱ(Unknown Source:58)
	at com.fkzhang.wechatxposedhooks.ﹳˏ.ˎᵔ.ـᵎ(Unknown Source:60)
	at com.fkzhang.wechatxposedhooks.ʻʼ.ˈـ$יᴵ.beforeHookedMethod(Unknown Source:92)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(LspHooker.java:72)
	at LspHooker_.hook(Unknown Source:24)
	at com.tencent.wcdb.database.SQLiteDatabase.insert(SourceFile:1531)
	at com.tencent.mm.cf.f.insert(SourceFile:680)
	at com.tencent.mm.cf.h.a(SourceFile:567)
	at com.tencent.mm.storage.bj.c(SourceFile:1586)
	at com.tencent.mm.storage.bj.Z(SourceFile:1529)
	at com.tencent.mm.model.be.l(SourceFile:185)
	at com.tencent.mm.model.e.b(SourceFile:145)
	at com.tencent.mm.plugin.messenger.foundation.c.a(SourceFile:165)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(LspHooker.java:92)
	at LspHooker_.hook(Unknown Source:11)
	at com.tencent.mm.plugin.messenger.foundation.c.a(SourceFile:1059)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(LspHooker.java:92)
	at LspHooker_.hook(Unknown Source:24)
	at com.tencent.mm.plugin.messenger.foundation.f.a(SourceFile:84)
	at com.tencent.mm.plugin.zero.c.a(SourceFile:57)
	at com.tencent.mm.modelmulti.o$a$1.Av(SourceFile:785)
	at com.tencent.mm.sdk.platformtools.ap.handleMessage(SourceFile:69)
	at com.tencent.mm.sdk.platformtools.am.handleMessage(SourceFile:185)
	at com.tencent.mm.sdk.platformtools.am.dispatchMessage(SourceFile:140)
	at android.os.Looper.loop(Looper.java:239)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.tencent.mm.sdk.g.c.c$1$1.run(SourceFile:39)

2021-03-03 09:31:26.026 6914-7003/com.tencent.mm LSPosedBridge: java.lang.NoSuchMethodError: com.tencent.mm.storage.u#()#bestmatch
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ـﾞ.ʽﹳ(:2)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ـﾞ.ˎˊ(:1)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ᐧᐧ.ʿˎ(:2)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˑʾ.ˑᵢ.ˉˉ(Unknown Source:51)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˑʾ.ˑᵢ$ˊᵔ.ˎˊ(:1)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ˑʾ.ˎˊ(:1)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ﹳʿ.ﹳʿ(Unknown Source:16)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ﹳʿ.ʻـ(Unknown Source:33)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˑʾ.ʿᵢ.ˎˊ(:6)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ˑʾ.ˎˊ(:1)
	at ˎˊ.ʼـ.ˎˊ.ˎˊ.ˊ.ﹳʿ.ﹳʿ(Unknown Source:16)
	at com.fkzhang.wxfeatures.base.Wrapper.Init.publish(:2)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1283)
	at com.fkzhang.wechatxposedhooks.ᵎˏ.יᴵ.ᵎـ(Unknown Source:22)
	at com.fkzhang.wechatxposedhooks.ᵎˏ.ᵔﹶ.ˎⁱ(Unknown Source:58)
	at com.fkzhang.wechatxposedhooks.ﹳˏ.ˎᵔ.ـᵎ(Unknown Source:60)
	at com.fkzhang.wechatxposedhooks.ʻʼ.ˈـ$יᴵ.beforeHookedMethod(Unknown Source:92)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(LspHooker.java:72)
	at LspHooker_.hook(Unknown Source:24)
	at com.tencent.wcdb.database.SQLiteDatabase.insert(SourceFile:1531)
	at com.tencent.mm.cf.f.insert(SourceFile:680)
	at com.tencent.mm.cf.h.a(SourceFile:567)
	at com.tencent.mm.storage.bj.c(SourceFile:1586)
	at com.tencent.mm.storage.bj.Z(SourceFile:1529)
	at com.tencent.mm.model.be.l(SourceFile:185)
	at com.tencent.mm.model.e.b(SourceFile:145)
	at com.tencent.mm.plugin.messenger.foundation.c.a(SourceFile:165)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(LspHooker.java:92)
	at LspHooker_.hook(Unknown Source:11)
	at com.tencent.mm.plugin.messenger.foundation.c.a(SourceFile:1059)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(LspHooker.java:92)
	at LspHooker_.hook(Unknown Source:24)
	at com.tencent.mm.plugin.messenger.foundation.f.a(SourceFile:84)
	at com.tencent.mm.plugin.zero.c.a(SourceFile:57)
	at com.tencent.mm.modelmulti.o$a$1.Av(SourceFile:785)
	at com.tencent.mm.sdk.platformtools.ap.handleMessage(SourceFile:69)
	at com.tencent.mm.sdk.platformtools.am.handleMessage(SourceFile:185)
	at com.tencent.mm.sdk.platformtools.am.dispatchMessage(SourceFile:140)
	at android.os.Looper.loop(Looper.java:239)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.tencent.mm.sdk.g.c.c$1$1.run(SourceFile:39)
[LSPosed_Modules_20210303_174939.log](https://github.com/fkzhang/WechatUnrecalled/files/6075074/LSPosed_Modules_20210303_174939.log)

**Comment by msfbao** [comment]
现在遇到的问题就是 自定义铃声 有时会响 有时不会响 不知要怎么处理

**Comment by msfbao** [comment]
谢谢大神的更新 现在正常了
