### ISSUE TITLE
开启wx后，微信闪退

### ISSUE THREAD

**Issue by Ludwig-OG** [fkzhang/WechatUnrecalled#484]
2021-03-04 04:52:25.025 25721-25774/com.tencent.mm LSPosedBridge: Wechat: 8.0.1_1840 {64bit} (0x2800013b)[690522c2]
2021-03-04 04:52:26.026 25865-25865/com.tencent.mm LSPosedBridge: com.tencent.mm loading com.fkzhang.wechatxposed
2021-03-04 04:52:26.026 25865-25865/com.tencent.mm LSPosedBridge: feature loaded: themes 40
2021-03-04 04:52:26.026 25865-25916/com.tencent.mm LSPosedBridge: 1: true
2021-03-04 04:52:26.026 25865-25916/com.tencent.mm LSPosedBridge: 2: true
2021-03-04 04:52:26.026 25865-25916/com.tencent.mm LSPosedBridge: 3: true
2021-03-04 04:52:26.026 25865-25916/com.tencent.mm LSPosedBridge: 4: true
2021-03-04 04:52:26.026 25865-25917/com.tencent.mm LSPosedBridge: 微X模块 2.21_3.17 ()(6,89) p
2021-03-04 04:52:26.026 25865-25865/com.tencent.mm LSPosedBridge: com.fkzhang.wechatxposed [WechatXposed](2.21|83): wechat version 8.0.1(1840)
2021-03-04 04:52:26.026 25865-25865/com.tencent.mm LSPosedBridge: com.fkzhang.wechatxposed load time: 620
2021-03-04 04:52:26.026 25865-25865/com.tencent.mm LSPosedBridge: java.lang.ExceptionInInitializerError
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callStaticMethod(Unknown Source:5)
	at com.fkzhang.wechatxposedhooks.ᵎʾ.ᵎʾ.ˑﾞ(Unknown Source:31)
	at com.fkzhang.wechatxposedhooks.ᵎʾ.ᵎʾ.ﹶˏ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ᵎʾ.ᵎʾ$ˏᴵ.ˑᵔ(Unknown Source:2)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ᵎʾ(Unknown Source:28)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ˑʾ(Unknown Source:16)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ˑⁱ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˋـ.ˏʻ(Unknown Source:16)
	at com.fkzhang.wechatxposedhooks.ᵎʾ.יʻ.ᵎʾ(Unknown Source:65)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ⁱʼ.ـˈ(Unknown Source:37)
	at com.fkzhang.wechatxposedhooks.ᵎʾ.ᵎʾ$ʿˉ.ˑᵔ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ᵎʾ(Unknown Source:28)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ˑʾ(Unknown Source:16)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ˑⁱ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ˑᵔ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˋـ.ˑᵔ(Unknown Source:16)
	at com.fkzhang.wechatxposedhooks.Wrapper.FPB.gb(Unknown Source:4)
	at java.lang.reflect.Method.invoke(Native Method)
	at ʼٴ.ᐧʼ.ʼٴ.ʼٴ.ᐧʼ.ˎⁱ.ʼٴ(:4)
	at ʼٴ.ᐧʼ.ʼٴ.ʼٴ.ﾞ.ʼٴ.ˏᐧ(:2)
	at ʼٴ.ᐧʼ.ʼٴ.ʼٴ.ʼי.ʾˎ.ᵢʼ(Unknown Source:17)
	at ʼٴ.ᐧʼ.ʼٴ.ʼٴ.ˏˋ.ˉـ.ʼٴ(:4)
	at ʼٴ.ᐧʼ.ʼٴ.ʼٴ.ᐧʼ.ﾞ.ʼٴ(:1)
	at ʼٴ.ᐧʼ.ʼٴ.ʼٴ.ᐧʼ.ˎⁱ.ﾞ(Unknown Source:16)
	at com.fkzhang.wxfeatures.themes.Wrapper.Init.publish(:2)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	at com.fkzhang.wechatxposedhooks.ˑʾ.ⁱʼ.ʼᵢ(Unknown Source:22)
	at com.fkzhang.wechatxposedhooks.ˑʾ.ˑᵔ.ʼᐧ(Unknown Source:58)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˋـ.ʻʽ(Unknown Source:60)
	at com.fkzhang.wechatxposedhooks.יʻ.ᵎʾ$ⁱʼ.beforeHookedMethod(Unknown Source:92)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.hook(Unknown Source:11)
	at android.view.View.<init>(View.java:6191)
	at android.view.ViewGroup.<init>(ViewGroup.java:687)
	at android.widget.LinearLayout.<init>(LinearLayout.java:254)
	at android.widget.LinearLayout.<init>(LinearLayout.java:250)
	at android.widget.LinearLayout.<init>(LinearLayout.java:246)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
	at android.view.LayoutInflater.createView(LayoutInflater.java:776)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:930)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:950)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at android.widget.Toast.makeText(Toast.java:636)
	at android.widget.Toast.makeText(Toast.java:586)
	at android.xiaolan.beautify.toast.tools.hook.impi.AttachContext.afterHookedMethod(Unknown Source:4558)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.hook(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1288)
	at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7152)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.hook(Unknown Source:11)
	at android.app.ActivityThread.access$1600(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at com.tencent.mm.kernel.a.b.g.bM(SourceFile:3364)
	at com.tencent.mm.kernel.a.c.bA(SourceFile:121)
	at com.tencent.mm.kernel.g$2.a(SourceFile:192)
	at com.tencent.mm.kernel.c$1.a(SourceFile:69)
	at com.tencent.mm.kernel.c.d.c(SourceFile:91)
	at com.tencent.mm.kernel.c.a(SourceFile:272)
	at com.tencent.mm.kernel.g.b(SourceFile:395)
	at com.tencent.mm.ui.LauncherUI.<clinit>(SourceFile:172)
	... 71 more

2021-03-04 04:52:26.026 25865-25865/com.tencent.mm LSPosedBridge: java.lang.NoClassDefFoundError: com.tencent.mm.ui.LauncherUI
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callStaticMethod(Unknown Source:5)
	at com.fkzhang.wechatxposedhooks.ᵎʾ.ᵎʾ.ˑﾞ(Unknown Source:31)
	at com.fkzhang.wechatxposedhooks.ᵎʾ.ᵎʾ.ﹶˏ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ᵎʾ.ᵎʾ$ˏᴵ.ˑᵔ(Unknown Source:2)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ᵎʾ(Unknown Source:28)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ʻʼ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˋـ.ˆˊ(Unknown Source:16)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ⁱʼ.ـˈ(Unknown Source:114)
	at com.fkzhang.wechatxposedhooks.ᵎʾ.ᵎʾ$ʿˉ.ˑᵔ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ᵎʾ(Unknown Source:28)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ˑʾ(Unknown Source:16)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ˑⁱ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ˑᵔ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˋـ.ˑᵔ(Unknown Source:16)
	at com.fkzhang.wechatxposedhooks.Wrapper.FPB.gb(Unknown Source:4)
	at java.lang.reflect.Method.invoke(Native Method)
	at ʼٴ.ᐧʼ.ʼٴ.ʼٴ.ᐧʼ.ˎⁱ.ʼٴ(:4)
	at ʼٴ.ᐧʼ.ʼٴ.ʼٴ.ﾞ.ʼٴ.ˏᐧ(:2)
	at ʼٴ.ᐧʼ.ʼٴ.ʼٴ.ʼי.ʾˎ.ᵢʼ(Unknown Source:17)
	at ʼٴ.ᐧʼ.ʼٴ.ʼٴ.ˏˋ.ˉـ.ʼٴ(:4)
	at ʼٴ.ᐧʼ.ʼٴ.ʼٴ.ᐧʼ.ﾞ.ʼٴ(:1)
	at ʼٴ.ᐧʼ.ʼٴ.ʼٴ.ᐧʼ.ˎⁱ.ﾞ(Unknown Source:16)
	at com.fkzhang.wxfeatures.themes.Wrapper.Init.publish(:2)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	at com.fkzhang.wechatxposedhooks.ˑʾ.ⁱʼ.ʼᵢ(Unknown Source:22)
	at com.fkzhang.wechatxposedhooks.ˑʾ.ˑᵔ.ʼᐧ(Unknown Source:58)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˋـ.ʻʽ(Unknown Source:60)
	at com.fkzhang.wechatxposedhooks.יʻ.ᵎʾ$ⁱʼ.beforeHookedMethod(Unknown Source:92)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:75)
	at LspHooker_.hook(Unknown Source:11)
	at android.view.View.<init>(View.java:6191)
	at android.view.ViewGroup.<init>(ViewGroup.java:687)
	at android.widget.LinearLayout.<init>(LinearLayout.java:254)
	at android.widget.LinearLayout.<init>(LinearLayout.java:250)
	at android.widget.LinearLayout.<init>(LinearLayout.java:246)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
	at android.view.LayoutInflater.createView(LayoutInflater.java:776)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:930)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:950)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at android.widget.Toast.makeText(Toast.java:636)
	at android.widget.Toast.makeText(Toast.java:586)
	at android.xiaolan.beautify.toast.tools.hook.impi.AttachContext.afterHookedMethod(Unknown Source:4558)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.hook(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1157)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1288)
	at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7152)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.hook(Unknown Source:11)
	at android.app.ActivityThread.access$1600(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callStaticMethod(Unknown Source:5)
	at com.fkzhang.wechatxposedhooks.ᵎʾ.ᵎʾ.ˑﾞ(Unknown Source:31)
	at com.fkzhang.wechatxposedhooks.ᵎʾ.ᵎʾ.ﹶˏ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ᵎʾ.ᵎʾ$ˏᴵ.ˑᵔ(Unknown Source:2)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ᵎʾ(Unknown Source:28)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ˑʾ(Unknown Source:16)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˑʾ.ˑⁱ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ˋـ.ˏʻ(Unknown Source:16)
	at com.fkzhang.wechatxposedhooks.ᵎʾ.יʻ.ᵎʾ(Unknown Source:65)
	at com.fkzhang.wechatxposedhooks.ˏʻ.ⁱʼ.ـˈ(Unknown Source:37)
	... 60 more
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at com.tencent.mm.kernel.a.b.g.bM(SourceFile:3364)
	at com.tencent.mm.kernel.a.c.bA(SourceFile:121)
	at com.tencent.mm.kernel.g$2.a(SourceFile:192)
	at com.tencent.mm.kernel.c$1.a(SourceFile:69)
	at com.tencent.mm.kernel.c.d.c(SourceFile:91)
	at com.tencent.mm.kernel.c.a(SourceFile:272)
	at com.tencent.mm.kernel.g.b(SourceFile:395)
	at com.tencent.mm.ui.LauncherUI.<clinit>(SourceFile:172)
	... 71 more

**Comment by Ludwig-OG** [comment]
[LSPosed_Modules_20210304_125618.log](https://github.com/fkzhang/WechatUnrecalled/files/6081027/LSPosed_Modules_20210304_125618.log)

**Comment by Ludwig-OG** [comment]
[Uploading LSPosed_Verbose_20210304_130801.log…]()

**Comment by Starry483** [comment]
你好 用的是play商店版的微信吗 如果是的话就试试开启speed模式优化 我这里用着正常
