### ISSUE TITLE
微信8.02 Googleplay版本  微X模块无效

### ISSUE THREAD

**Issue by GOUKI9999** [fkzhang/WechatUnrecalled#490]
LSPosed模块1.45/46/47都有该问题，手机一加9，系统氧  日志开头处有以上信息

因为googleplay版本半年没有更新，下载了来自（相对可信？）第三方源的google play版本微信8.02
WeChat 8.0.2-1848 ARM64,7a for Google Play  [2021/06/11]

这一版本可以在微信的设置中看到微x模块选项但点击无效，配置微X模块处显示Xposed框架没有安装
wx lib not found，有这一错误提示在日志当中

尝试过重启，重新安装框架（更新），重新升级安装微x模块 2.21/2.22，都没法解决
希望开发者能够看到协助解决谢谢

日志如下

LSPosed Log
--------- beginning of information
Manufacturer: OnePlus
Brand: OnePlus
Device: OnePlus9
Product: OnePlus9
Model: LE2110
Fingerprint: OnePlus/OnePlus9_EEA/OnePlus9:11/RKQ1.201105.002/2106092118:user/release-keys
ROM description: OnePlus9-user 11   release-keys
Architecture: arm64-v8a
Android build: RKQ1.201105.002
Android version: 11
Android sdk: 30
LSPosed version: v1.4.7 (5803)
Riru version: v25.4.4.r426.05efc94 (426)
Riru api: 25
Magisk: f822ca5b (23001)
2021-07-01 06:06:20.020 I/com.tencent.mm(10511-10511): com.tencent.mm loading com.fkzhang.wechatxposed
2021-07-01 06:06:20.020 I/com.tencent.mm(10511-10511): wx lib not found!
2021-07-01 06:06:20.020 E/com.tencent.mm(10511-10511): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.fkzhang.wechatxposedhooks.ـﾞ.ʻˎ.ˏʿ(java.lang.String, boolean)' on a null object reference
	at com.fkzhang.wechatxposedhooks.ﹶᵢ.ᵔⁱ.ˉᵢ(Unknown Source:17)
	at com.fkzhang.wechatxposedhooks.ﹶᵢ.ᵔⁱ.ـʾ(Unknown Source:104)
	at com.fkzhang.wechatxposedhooks.WxJniCoreBridge.ـˉ(Unknown Source:41)
	at com.fkzhang.wechatxposedhooks.WxJniCoreBridge.ﾞـ(Unknown Source:0)
	at com.fkzhang.wechatxposedhooks.ᵎـ.ᴵˉ.ﹶᵢ(Unknown Source:59)
	at com.fkzhang.wechatxposedhooks.ᵎـ.ᴵˉ.<init>(Unknown Source:62)
	at com.fkzhang.wechatxposedhooks.Wrapper.HookWrapper.<init>(Unknown Source:0)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at de.robv.android.xposed.XposedHelpers.newInstance(Unknown Source:4)
	at com.fkzhang.xposed.hook.ᐧـ.ʼﾞ(Unknown Source:36)
	at com.fkzhang.xposed.hook.ᐧـ.ٴﹶ(Unknown Source:1)
	at com.fkzhang.xposed.hook.WxCoreLoader.ʽﹳ(Unknown Source:14)
	at com.fkzhang.wechatxposed.ˊᵎ.ˑᵔ(Unknown Source:2)
	at com.fkzhang.xposed.hook.יˉ.ˉٴ(Unknown Source:267)
	at com.fkzhang.xposed.hook.יˉ.ˊᵎ(Unknown Source:0)
	at com.fkzhang.xposed.hook.יˉ$ʼˆ.afterHookedMethod(Unknown Source:53)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.attachBaseContext(Unknown Source:11)
	at android.app.Application.attach(Application.java:371)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1165)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1236)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6967)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1700(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2098)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8035)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

2021-07-01 06:06:20.020 E/com.tencent.mm(10511-10511): de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.fkzhang.wechatxposedhooks.ـﾞ.ʻˎ.ˏʿ(java.lang.String, boolean)' on a null object reference
	at de.robv.android.xposed.XposedHelpers.newInstance(Unknown Source:27)
	at com.fkzhang.xposed.hook.ᐧـ.ʼﾞ(Unknown Source:36)
	at com.fkzhang.xposed.hook.ᐧـ.ٴﹶ(Unknown Source:1)
	at com.fkzhang.xposed.hook.WxCoreLoader.ʽﹳ(Unknown Source:14)
	at com.fkzhang.wechatxposed.ˊᵎ.ˑᵔ(Unknown Source:2)
	at com.fkzhang.xposed.hook.יˉ.ˉٴ(Unknown Source:267)
	at com.fkzhang.xposed.hook.יˉ.ˊᵎ(Unknown Source:0)
	at com.fkzhang.xposed.hook.יˉ$ʼˆ.afterHookedMethod(Unknown Source:53)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.attachBaseContext(Unknown Source:11)
	at android.app.Application.attach(Application.java:371)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1165)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1236)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6967)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1700(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2098)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8035)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.fkzhang.wechatxposedhooks.ـﾞ.ʻˎ.ˏʿ(java.lang.String, boolean)' on a null object reference
	at com.fkzhang.wechatxposedhooks.ﹶᵢ.ᵔⁱ.ˉᵢ(Unknown Source:17)
	at com.fkzhang.wechatxposedhooks.ﹶᵢ.ᵔⁱ.ʻי(Unknown Source:59)
	at com.fkzhang.wechatxposedhooks.ᵎـ.ᴵˉ.ﹶᵢ(Unknown Source:265)
	at com.fkzhang.wechatxposedhooks.ᵎـ.ᴵˉ.<init>(Unknown Source:62)
	at com.fkzhang.wechatxposedhooks.Wrapper.HookWrapper.<init>(Unknown Source:0)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at de.robv.android.xposed.XposedHelpers.newInstance(Unknown Source:4)
	... 24 more

2021-07-01 06:06:20.020 I/com.tencent.mm(10511-10511): com.fkzhang.wechatxposed load hooks failed!
2021-07-01 06:06:20.020 I/com.tencent.mm(10511-10511): com.fkzhang.wechatxposed load time: 60
2021-07-01 06:06:21.021 I/com.tencent.mobileqq(11353-11353): com.tencent.mobileqq loading com.fkzhang.qqxposed
2021-07-01 06:06:22.022 E/com.tencent.mobileqq(11353-11353): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: bdbt
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:13)
	at com.fkzhang.qqxposedhooks.ˑʽ.ˆﹶ.ˎˆ(Unknown Source:18)
	at com.fkzhang.qqxposedhooks.ˎˆ.ʾˎ.ـˉ(Unknown Source:86)
	at com.fkzhang.qqxposedhooks.ˎˆ.ˎⁱ.ᴵʾ(Unknown Source:0)
	at com.fkzhang.qqxposedhooks.ˎˆ.ˎⁱ.hook(Unknown Source:307)
	at com.fkzhang.qqxposedhooks.ˎˆ.ᵢˈ.ـˉ(Unknown Source:4)
	at com.fkzhang.qqxposedhooks.ˎˆ.ᵢˈ.hook(Unknown Source:0)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	at com.fkzhang.xposed.hook.ᐧˎ.יʻ(Unknown Source:59)
	at com.fkzhang.xposed.hook.ᐧˎ.ˈⁱ(Unknown Source:1)
	at com.fkzhang.xposed.hook.QxCoreLoader.ˈי(Unknown Source:17)
	at com.fkzhang.qqxposed.ᴵˉ.ﹳʽ(Unknown Source:2)
	at com.fkzhang.xposed.hook.ⁱʽ$ᵎʼ.run(Unknown Source:205)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8035)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.ClassNotFoundException: bdbt
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at x0.a(Unknown Source:24)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:5)
	... 20 more
Caused by: java.lang.ClassNotFoundException: bdbt
	... 24 more

2021-07-01 06:06:22.022 E/com.tencent.mobileqq(11353-11353): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mobileqq.widget.FormCommonSingleLineItem
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:13)
	at com.fkzhang.qqxposedhooks.ˑʽ.ˆﹶ.ˎˆ(Unknown Source:18)
	at com.fkzhang.qqxposedhooks.ˎˆ.ʾˎ.ـˉ(Unknown Source:247)
	at com.fkzhang.qqxposedhooks.ˎˆ.ˎⁱ.ᴵʾ(Unknown Source:0)
	at com.fkzhang.qqxposedhooks.ˎˆ.ˎⁱ.hook(Unknown Source:307)
	at com.fkzhang.qqxposedhooks.ˎˆ.ᵢˈ.ـˉ(Unknown Source:4)
	at com.fkzhang.qqxposedhooks.ˎˆ.ᵢˈ.hook(Unknown Source:0)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	at com.fkzhang.xposed.hook.ᐧˎ.יʻ(Unknown Source:59)
	at com.fkzhang.xposed.hook.ᐧˎ.ˈⁱ(Unknown Source:1)
	at com.fkzhang.xposed.hook.QxCoreLoader.ˈי(Unknown Source:17)
	at com.fkzhang.qqxposed.ᴵˉ.ﹳʽ(Unknown Source:2)
	at com.fkzhang.xposed.hook.ⁱʽ$ᵎʼ.run(Unknown Source:205)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8035)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.ClassNotFoundException: com.tencent.mobileqq.widget.FormCommonSingleLineItem
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at x0.a(Unknown Source:24)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:5)
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.tencent.mobileqq.widget.FormCommonSingleLineItem
	... 24 more

2021-07-01 06:06:22.022 E/com.tencent.mobileqq(11353-11353): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.tencent.mobileqq.activity.aio.item.PokeItemBuilder
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:13)
	at com.fkzhang.qqxposedhooks.ˑʽ.ˆﹶ.ˎˆ(Unknown Source:18)
	at com.fkzhang.qqxposedhooks.ˎˆ.ʾˎ.ـˉ(Unknown Source:316)
	at com.fkzhang.qqxposedhooks.ˎˆ.ˎⁱ.ᴵʾ(Unknown Source:0)
	at com.fkzhang.qqxposedhooks.ˎˆ.ˎⁱ.hook(Unknown Source:307)
	at com.fkzhang.qqxposedhooks.ˎˆ.ᵢˈ.ـˉ(Unknown Source:4)
	at com.fkzhang.qqxposedhooks.ˎˆ.ᵢˈ.hook(Unknown Source:0)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.XposedHelpers.callMethod(Unknown Source:8)
	at com.fkzhang.xposed.hook.ᐧˎ.יʻ(Unknown Source:59)
	at com.fkzhang.xposed.hook.ᐧˎ.ˈⁱ(Unknown Source:1)
	at com.fkzhang.xposed.hook.QxCoreLoader.ˈי(Unknown Source:17)
	at com.fkzhang.qqxposed.ᴵˉ.ﹳʽ(Unknown Source:2)
	at com.fkzhang.xposed.hook.ⁱʽ$ᵎʼ.run(Unknown Source:205)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8035)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.ClassNotFoundException: com.tencent.mobileqq.activity.aio.item.PokeItemBuilder
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at x0.a(Unknown Source:24)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:5)
	... 20 more
Caused by: java.lang.ClassNotFoundException: com.tencent.mobileqq.activity.aio.item.PokeItemBuilder
	... 24 more

**Comment by JusufUs** [comment]
同样遇到这个问题
使用tg频道分享的覆盖安装8.0.11也是，设置里面显示微X，点不进去

**Comment by QGB** [comment]
lsposed 微信 “xposed框架没有安装”
