### ISSUE TITLE
 Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by BigBigBIgMan** [fkzhang/WechatUnrecalled#510]
`[ 2023-04-01T11:15:13.369    10220: 27592: 27592 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:21:25.057    10077: 30343: 30343 I/LSPosed-Bridge  ] Loading module com.coderstory.toolkit from /data/app/~~y0kKbNzHeG4GIbrA00WOSw==/com.coderstory.toolkit-ovPqSnu9YxRNMfjDo2NoNQ==/base.apk
[ 2023-04-01T11:21:25.058    10077: 30343: 30343 I/LSPosed-Bridge  ]   Loading class toolkit.coderstory.MainHook
[ 2023-04-01T11:21:31.906    10220: 30730: 30730 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~7ooXu2e_nc7kfoLBK-sOww==/com.fkzhang.wechatxposed-fmoPXVCK1S3gBb7GvBYP8g==/base.apk
[ 2023-04-01T11:21:31.915    10220: 30730: 30730 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:21:33.421    10220: 30730: 30730 I/LSPosed-Bridge  ] WeXposed: com.tencent.mm loading com.fkzhang.wechatxposed
[ 2023-04-01T11:21:34.530    10220: 30730: 30730 I/LSPosed-Bridge  ] WeXposed: wxcore (153) loaded successfully!
[ 2023-04-01T11:21:34.531    10220: 30730: 30730 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed [WechatXposed](2.39|104): wechat version 8.0.33(2320)
[ 2023-04-01T11:21:34.531    10220: 30730: 30730 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed load time: 1233
[ 2023-04-01T11:21:42.946    10220: 30730: 30774 I/LSPosed-Bridge  ] WeXposed: 微X模块 2.39_4.32 (9,153) p
[ 2023-04-01T11:21:42.947    10220: 30730: 30774 I/LSPosed-Bridge  ] WeXposed: Wechat: 8.0.33_2320 {64,arm64} (0x28002137)[ae09f328]
[ 2023-04-01T11:21:43.210    10220: 30730: 30773 I/LSPosed-Bridge  ] WeXposed: feature loaded: base 395
[ 2023-04-01T11:21:43.411    10220: 30730: 30773 I/LSPosed-Bridge  ] WeXposed: feature loaded: donation 21
[ 2023-04-01T11:21:55.906    10220: 31415: 31415 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~7ooXu2e_nc7kfoLBK-sOww==/com.fkzhang.wechatxposed-fmoPXVCK1S3gBb7GvBYP8g==/base.apk
[ 2023-04-01T11:21:55.918    10220: 31415: 31415 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:28:48.398    10220:  4359:  4359 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~7ooXu2e_nc7kfoLBK-sOww==/com.fkzhang.wechatxposed-fmoPXVCK1S3gBb7GvBYP8g==/base.apk
[ 2023-04-01T11:28:48.408    10220:  4359:  4359 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:28:48.929    10220:  4359:  4359 I/LSPosed-Bridge  ] WeXposed: com.tencent.mm loading com.fkzhang.wechatxposed
[ 2023-04-01T11:28:49.243    10220:  4359:  4359 I/LSPosed-Bridge  ] WeXposed: wxcore (153) loaded successfully!
[ 2023-04-01T11:28:49.243    10220:  4359:  4359 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed [WechatXposed](2.39|104): wechat version 8.0.33(2320)
[ 2023-04-01T11:28:49.243    10220:  4359:  4359 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed load time: 354
[ 2023-04-01T11:28:49.380    10220:  4359:  4359 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.mm/com.tencent.mm.ui.LauncherUI}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.res.Resources.addLoaders(android.content.res.loader.ResourcesLoader[])' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3763)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3937)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.res.Resources.addLoaders(android.content.res.loader.ResourcesLoader[])' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3706)
	... 12 more
[ 2023-04-01T11:28:49.761    10220:  4635:  4635 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~7ooXu2e_nc7kfoLBK-sOww==/com.fkzhang.wechatxposed-fmoPXVCK1S3gBb7GvBYP8g==/base.apk
[ 2023-04-01T11:28:49.773    10220:  4635:  4635 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:28:49.921    10220:  4735:  4735 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~7ooXu2e_nc7kfoLBK-sOww==/com.fkzhang.wechatxposed-fmoPXVCK1S3gBb7GvBYP8g==/base.apk
[ 2023-04-01T11:28:49.937    10220:  4735:  4735 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:28:52.087    10220:  4359:  4502 I/LSPosed-Bridge  ] WeXposed: 微X模块 2.39_4.32 (9,153) p
[ 2023-04-01T11:28:52.088    10220:  4359:  4502 I/LSPosed-Bridge  ] WeXposed: Wechat: 8.0.33_2320 {64,arm64} (0x28002137)[ae09f328]
[ 2023-04-01T11:28:52.143    10220:  4359:  4497 I/LSPosed-Bridge  ] WeXposed: feature loaded: base 395
[ 2023-04-01T11:28:52.292    10220:  4359:  4497 I/LSPosed-Bridge  ] WeXposed: feature loaded: donation 21
[ 2023-04-01T11:29:16.310    10220:  6172:  6172 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~7ooXu2e_nc7kfoLBK-sOww==/com.fkzhang.wechatxposed-fmoPXVCK1S3gBb7GvBYP8g==/base.apk
[ 2023-04-01T11:29:16.320    10220:  6172:  6172 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:29:17.645    10220:  6172:  6172 I/LSPosed-Bridge  ] WeXposed: com.tencent.mm loading com.fkzhang.wechatxposed
[ 2023-04-01T11:29:18.662    10220:  6172:  6172 I/LSPosed-Bridge  ] WeXposed: wxcore (153) loaded successfully!
[ 2023-04-01T11:29:18.663    10220:  6172:  6172 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed [WechatXposed](2.39|104): wechat version 8.0.33(2320)
[ 2023-04-01T11:29:18.663    10220:  6172:  6172 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed load time: 1051
`

**Comment by BigBigBIgMan** [comment]
[ 2023-04-01T11:15:13.369    10220: 27592: 27592 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:21:25.057    10077: 30343: 30343 I/LSPosed-Bridge  ] Loading module com.coderstory.toolkit from /data/app/~~y0kKbNzHeG4GIbrA00WOSw==/com.coderstory.toolkit-ovPqSnu9YxRNMfjDo2NoNQ==/base.apk
[ 2023-04-01T11:21:25.058    10077: 30343: 30343 I/LSPosed-Bridge  ]   Loading class toolkit.coderstory.MainHook
[ 2023-04-01T11:21:31.906    10220: 30730: 30730 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~7ooXu2e_nc7kfoLBK-sOww==/com.fkzhang.wechatxposed-fmoPXVCK1S3gBb7GvBYP8g==/base.apk
[ 2023-04-01T11:21:31.915    10220: 30730: 30730 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:21:33.421    10220: 30730: 30730 I/LSPosed-Bridge  ] WeXposed: com.tencent.mm loading com.fkzhang.wechatxposed
[ 2023-04-01T11:21:34.530    10220: 30730: 30730 I/LSPosed-Bridge  ] WeXposed: wxcore (153) loaded successfully!
[ 2023-04-01T11:21:34.531    10220: 30730: 30730 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed [WechatXposed](2.39|104): wechat version 8.0.33(2320)
[ 2023-04-01T11:21:34.531    10220: 30730: 30730 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed load time: 1233
[ 2023-04-01T11:21:42.946    10220: 30730: 30774 I/LSPosed-Bridge  ] WeXposed: 微X模块 2.39_4.32 (9,153) p
[ 2023-04-01T11:21:42.947    10220: 30730: 30774 I/LSPosed-Bridge  ] WeXposed: Wechat: 8.0.33_2320 {64,arm64} (0x28002137)[ae09f328]
[ 2023-04-01T11:21:43.210    10220: 30730: 30773 I/LSPosed-Bridge  ] WeXposed: feature loaded: base 395
[ 2023-04-01T11:21:43.411    10220: 30730: 30773 I/LSPosed-Bridge  ] WeXposed: feature loaded: donation 21
[ 2023-04-01T11:21:55.906    10220: 31415: 31415 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~7ooXu2e_nc7kfoLBK-sOww==/com.fkzhang.wechatxposed-fmoPXVCK1S3gBb7GvBYP8g==/base.apk
[ 2023-04-01T11:21:55.918    10220: 31415: 31415 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:28:48.398    10220:  4359:  4359 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~7ooXu2e_nc7kfoLBK-sOww==/com.fkzhang.wechatxposed-fmoPXVCK1S3gBb7GvBYP8g==/base.apk
[ 2023-04-01T11:28:48.408    10220:  4359:  4359 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:28:48.929    10220:  4359:  4359 I/LSPosed-Bridge  ] WeXposed: com.tencent.mm loading com.fkzhang.wechatxposed
[ 2023-04-01T11:28:49.243    10220:  4359:  4359 I/LSPosed-Bridge  ] WeXposed: wxcore (153) loaded successfully!
[ 2023-04-01T11:28:49.243    10220:  4359:  4359 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed [WechatXposed](2.39|104): wechat version 8.0.33(2320)
[ 2023-04-01T11:28:49.243    10220:  4359:  4359 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed load time: 354
[ 2023-04-01T11:28:49.380    10220:  4359:  4359 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.mm/com.tencent.mm.ui.LauncherUI}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.res.Resources.addLoaders(android.content.res.loader.ResourcesLoader[])' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3763)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3937)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.res.Resources.addLoaders(android.content.res.loader.ResourcesLoader[])' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3706)
	... 12 more
[ 2023-04-01T11:28:49.761    10220:  4635:  4635 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~7ooXu2e_nc7kfoLBK-sOww==/com.fkzhang.wechatxposed-fmoPXVCK1S3gBb7GvBYP8g==/base.apk
[ 2023-04-01T11:28:49.773    10220:  4635:  4635 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:28:49.921    10220:  4735:  4735 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~7ooXu2e_nc7kfoLBK-sOww==/com.fkzhang.wechatxposed-fmoPXVCK1S3gBb7GvBYP8g==/base.apk
[ 2023-04-01T11:28:49.937    10220:  4735:  4735 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:28:52.087    10220:  4359:  4502 I/LSPosed-Bridge  ] WeXposed: 微X模块 2.39_4.32 (9,153) p
[ 2023-04-01T11:28:52.088    10220:  4359:  4502 I/LSPosed-Bridge  ] WeXposed: Wechat: 8.0.33_2320 {64,arm64} (0x28002137)[ae09f328]
[ 2023-04-01T11:28:52.143    10220:  4359:  4497 I/LSPosed-Bridge  ] WeXposed: feature loaded: base 395
[ 2023-04-01T11:28:52.292    10220:  4359:  4497 I/LSPosed-Bridge  ] WeXposed: feature loaded: donation 21
[ 2023-04-01T11:29:16.310    10220:  6172:  6172 I/LSPosed-Bridge  ] Loading module com.fkzhang.wechatxposed from /data/app/~~7ooXu2e_nc7kfoLBK-sOww==/com.fkzhang.wechatxposed-fmoPXVCK1S3gBb7GvBYP8g==/base.apk
[ 2023-04-01T11:29:16.320    10220:  6172:  6172 I/LSPosed-Bridge  ]   Loading class com.fkzhang.wechatxposed.XposedInit
[ 2023-04-01T11:29:17.645    10220:  6172:  6172 I/LSPosed-Bridge  ] WeXposed: com.tencent.mm loading com.fkzhang.wechatxposed
[ 2023-04-01T11:29:18.662    10220:  6172:  6172 I/LSPosed-Bridge  ] WeXposed: wxcore (153) loaded successfully!
[ 2023-04-01T11:29:18.663    10220:  6172:  6172 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed [WechatXposed](2.39|104): wechat version 8.0.33(2320)
[ 2023-04-01T11:29:18.663    10220:  6172:  6172 I/LSPosed-Bridge  ] WeXposed: com.fkzhang.wechatxposed load time: 1051
